### ISSUE TITLE
input模式默认readonly

### ISSUE THREAD

**Issue by kyokusan** [941477276/vue-country-intl#10]
添加修改方法  修改后不生效

**Comment by 941477276** [comment]
你说的这个问题已经解决，这个是由于之前项目中在ios设备上遇到了一个问题而进行的优化措施，在ios设备中选中了指定国籍后软键盘并不会自动收起来，必须用户手动将其收回，后面我就将input置为`readonly`了。现在我给组件加了`iosMobileReadonly`指令，可以更灵活配置了
