### ISSUE TITLE
使用该组件时不明原因报错

### ISSUE THREAD

**Issue by LiuCaptain** [941477276/vue-country-intl#13]
`<VueCountryIntl
              class="international_component"
              schema="popover"
              v-model="signData.interTelCode"
            >
              <button type="button" slot="reference" class="phone_code_button">
                <span>+{{ signData.interTelCode }}</span>
                <img
                  class="img"
                  src="./../common/img/xialaRegister.png"
                  alt=""
                />
              </button>
            </VueCountryIntl>`
当该组件外面再包裹一个div,div上加v-if控制显示隐藏，v-if为false隐藏式，控制台报不明原因错误，如下：
vue-country-intl.min.js?7479:1 Uncaught TypeError: Cannot read property 'style' of undefined
    at eval (vue-country-intl.min.js?7479:1)

**Comment by 941477276** [comment]
问题已解决，更新至最新版本即可

**Comment by xiaohuanggua12138** [comment]
怎么根据区号默认显示该区号对应的国籍信息

**Comment by 941477276** [comment]
`v-model`绑定的值为区号就可以，如：`86`、`+86`，前提是需设置`type="phone"`

**Comment by xiaohuanggua12138** [comment]
但是当加上iso2属性时，就不会显示出来，而不加上iso2属性的话，会在控制台抛出一个错误当type=phone时最好传递iso2属性，否则当区号代码为212或358时会出现选择不正确问题。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "941477276/vue-country-intl"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月19日(星期六) 上午10:32
收件人:&nbsp;"941477276/vue-country-intl"<vue-country-intl@noreply.github.com&gt;;
抄送:&nbsp;"小黄瓜。"<625365261@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [941477276/vue-country-intl] 使用该组件时不明原因报错 (#13)





 
v-model绑定的值为区号就可以，如：86、+86，前提是需设置type="phone"

**Comment by 941477276** [comment]
我这边测的不会呀，你参考下#20 的解决方案
