### ISSUE TITLE
使用组件时，出现不明bug

### ISSUE THREAD

**Issue by LiuCaptain** [941477276/vue-country-intl#14]
我使用scheme = popover 模式，当用户选择了一个国家，如果再次打开选择与上次相同国家，v-modle绑定的值变为空了，同时getSelected()方法返回的值也为空，该bug在演示网页页能呈现

**Comment by 941477276** [comment]
设计就是这样的，选择了一个国家，再次选择它就会变成取消选择

**Comment by LiuCaptain** [comment]
我们产品提出了这个bug，如果这样设计有点不符合实际使用的，因为国际化项目国际区号可定要存在，应该返回这个值，如果真的设计取消，可以返回这个值有我们前端开发控制比对前后值是否相同

**Comment by LiuCaptain** [comment]
值不返回，这就有点问题了

**Comment by 941477276** [comment]
你提的这个需求已经解决了，更新至1.0.24版本即可

**Comment by LiuCaptain** [comment]
已经安装上了，谢谢你！

**Comment by 941477276** [comment]
不客气
