### ISSUE TITLE
预览网址访问不了了

### ISSUE THREAD

**Issue by LiuCaptain** [941477276/vue-country-intl#17]
组件预览网址访问不了了

**Comment by 941477276** [comment]
可能需要翻墙，如果实在访问不了，那就把代码down下来运行下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "941477276/vue-country-intl"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月4日(星期二) 下午3:37
收件人:&nbsp;"941477276/vue-country-intl"<vue-country-intl@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[941477276/vue-country-intl] 预览网址访问不了了 (#17)





 
组件预览网址访问不了了
