### ISSUE TITLE
popoverClass添加自定义class时修改样式无效

### ISSUE THREAD

**Issue by huoyou** [941477276/vue-country-intl#2]
schema="popover"时，通过popoverClass添加自定义class修改样式无效，或者有没有别的方法可以修改最外层样式方法（style 去除scoped也无效）

**Comment by 941477276** [comment]
经我测试你说的这个问题并不存在呀
![WX20191122-161050](https://user-images.githubusercontent.com/20528541/69409010-184eaa80-0d43-11ea-81a1-24b16bc0970a.png)
![WX20191122-161212](https://user-images.githubusercontent.com/20528541/69409014-197fd780-0d43-11ea-97be-c2962f85fc6d.png)

**Comment by huoyou** [comment]
class是有，但是给这个class写样式不生效

**Comment by 941477276** [comment]
有起到作用的，我估计是你写的样式有问题，或者是你加了scoped
![image](https://user-images.githubusercontent.com/20528541/69409951-ef2f1980-0d44-11ea-870b-89967d2925d2.png)

**Comment by huoyou** [comment]
多谢大佬！我再试试
