### ISSUE TITLE
刚在新项目中下载安装组件后刷新页面首次点击组件时出现报错

### ISSUE THREAD

**Issue by LiuCaptain** [941477276/vue-country-intl#20]
出现报错： 当type=phone时最好传递iso2属性，否则当区号代码为212或358时会出现选择不正确问题！
我的组件属性已经有属性iso2  ，如下：
```
<VueCountryIntl  iso2  schema="popover"  v-model="phoneCountry" type="phone" @onChange="changeCountryCode">
            <div class="country_code" slot="reference">
              <span>+{{ phoneCountry }}</span>
            </div>
</VueCountryIntl>
```
请问要怎么解决呢

**Comment by 941477276** [comment]
可以不予理会，或者如下解决
```
<VueCountryIntl
        v-model="schemaInput.default"
        :iso2="schemaInput.selectedObjDefault.iso2"
        @onChange="onDefaultChange">
        <template slot="vueCountryNoData"><h1>没有找到该国籍！</h1></template>
</VueCountryIntl>

export default {
  name: 'app',
  data(){
    return {
      schemaInput: {
        default: '+86',
        selectedObjDefault: {}
      }
    }
  },
  methods: {
    onDefaultChange(selected){
      this.schemaInput.selectedObjDefault = selected;
    }
  }
}
</script>
```

**Comment by LiuCaptain** [comment]
不行 我按照你这个解决方法写，并且核对代码了多次。
这个问题还是会在页面刷新后第一次点击出现，报错。第二次开始点击不会报错了

**Comment by LiuCaptain** [comment]
我先用type=country类型吧，这个类型不会报错，不错我只好通过@onChange事件拿到用户选择的手机号国际区号了

**Comment by 941477276** [comment]
这个报错不会影响使用的，只是我用来提示开发人员



---原始邮件---
发件人: "Captain"<notifications@github.com&gt;
发送时间: 2020年8月12日(周三) 晚上8:12
收件人: "941477276/vue-country-intl"<vue-country-intl@noreply.github.com&gt;;
抄送: "health&amp;learning&amp;money"<941477276@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [941477276/vue-country-intl] 刚在新项目中下载安装组件后刷新页面首次点击组件时出现报错 (#20)




 
不行 我按照你这个解决方法写，并且核对代码了多次。
 这个问题还是会在页面刷新后第一次点击出现，报错。第二次开始点击不会报错了

**Comment by LiuCaptain** [comment]
好的， 非常感谢你抽空回复
