### ISSUE TITLE
有直接引入js和css版本么

### ISSUE THREAD

**Issue by bobt2018** [941477276/vue-country-intl#26]
请问有直接引入js和css版本么

**Comment by 941477276** [comment]
将`lib`目录下的`js`、`css`、`img`拷贝到你的项目中就可以

**Comment by bobt2018** [comment]
> 将`lib`目录下的`js`、`css`、`img`拷贝到你的项目中就可以

按照例1中的html结构和lib目录拷贝下来试了下，没有加载出下拉列表，样式也和原本的bootstrap风格不同。大虾有空出个html版本吧，目前github上面有intl-tel-input，但是目前就是缺少搜索功能，我觉得楼主这个很符合大多数人的需求

**Comment by 941477276** [comment]
已出html版demo
参考`public`目录下的`native.html`

**Comment by bobt2018** [comment]
> 已出html版demo
> 参考`public`目录下的`native.html`

好的，感谢！
