### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '_c')

### ISSUE THREAD

**Issue by surest-sky** [941477276/vue-country-intl#32]
![image](https://user-images.githubusercontent.com/29169847/139645605-d79dfeb0-ff07-4077-a6e8-f07dbb146f01.png)

![image](https://user-images.githubusercontent.com/29169847/139645622-73805310-e32f-45d6-8845-1cefbe74d5de.png)

![image](https://user-images.githubusercontent.com/29169847/139645637-4c906f78-974c-4969-9ac3-5a96c726aa5a.png)

vue-country-intl.min.js:1 
        
    Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '_c')
    at Proxy.o (vue-country-intl.min.js:1)
    at renderComponentRoot (runtime-core.esm-bundler.js:756)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:4526)
    at ReactiveEffect.run (reactivity.esm-bundler.js:160)
    at setupRenderEffect (runtime-core.esm-bundler.js:4652)
    at mountComponent (runtime-core.esm-bundler.js:4435)
    at processComponent (runtime-core.esm-bundler.js:4393)
    at patch (runtime-core.esm-bundler.js:3988)
    at mountChildren (runtime-core.esm-bundler.js:4184)
    at processFragment (runtime-core.esm-bundler.js:4352)

**Comment by 941477276** [comment]
What is the value of `form.value`?

**Comment by zwsn** [comment]
解决没,遇到同样的问题.form.value设置的86和空都一样.
<img width="826" alt="image" src="https://user-images.githubusercontent.com/42889307/163507345-d5c09eee-a917-4036-93a6-0b1d60714d66.png">

**Comment by 941477276** [comment]
你是在`vue3`中使用吗？麻烦把代码贴下

**Comment by zwsn** [comment]
是vue3

```
<script setup>
import VueCountryIntl from 'vue-country-intl';
import 'vue-country-intl/lib/vue-country-intl.css'
let phoneCountry = '';
</script>

<template>
        <VueCountryIntl v-model="phoneCountry"></VueCountryIntl>
<template>
```

**Comment by 941477276** [comment]
`vue3`中需要使用vue3版本的插件：`[vue3-country-intl]`(https://github.com/941477276/vue3-country-intl)

**Comment by zwsn** [comment]
🙏

**Comment by zwsn** [comment]
vue3版本一引入就无限报错
<img width="1144" alt="image" src="https://user-images.githubusercontent.com/42889307/163508364-49419c09-029b-4003-9f3c-169d34fe33ee.png">

**Comment by 941477276** [comment]
你安装的哪个版本？

**Comment by zwsn** [comment]
"vue3-country-intl": "^1.0.8"

**Comment by 941477276** [comment]
vue3版的使用方法是这样的：
```
/*****main.js****/
import Vue3CountryIntl from 'vue3-country-intl';
// 引入css
import 'vue3-country-intl/lib/vue3-country-intl.css'
import App from './App.vue';

const app = createApp(App);

// 全局注册组件
app.component(Vue3CountryIntl.name, Vue3CountryIntl);

/*****组件中使用****/
<template>
    <vue3-country-intl v-model="countryCode"></vue3-country-intl>
</template>
```

**Comment by zwsn** [comment]
引入后没报错,但是页面不显示组件内容,控制台显示组件没解析

<img width="992" alt="image" src="https://user-images.githubusercontent.com/42889307/163509619-773741c7-23b9-474a-b3a5-514ce5b308aa.png">

**Comment by 941477276** [comment]
可以正常使用的，刚上面的使用方式有点小问题，已做了修正
![image](https://user-images.githubusercontent.com/20528541/163510497-b47bdd12-63aa-41f5-b018-c10df6f3347f.png)

**Comment by zwsn** [comment]
🙏

**Comment by zwsn** [comment]
还是不显示
<img width="994" alt="image" src="https://user-images.githubusercontent.com/42889307/163510873-16aebe27-927c-4a12-866a-26b6d92827fd.png">

**Comment by 941477276** [comment]
你怎么使用的？

**Comment by zwsn** [comment]
按照你发的

/*****main.js****/
import Vue3CountryIntl from 'vue3-country-intl';
// 引入css
import 'vue3-country-intl/lib/vue3-country-intl.css'

const app = createApp();

// 全局注册组件
app.component(Vue3CountryIntl.name, Vue3CountryIntl);

/*****组件中使用****/
<template>
    <vue3-country-intl v-model="countryCode"></vue3-country-intl>
</template>

**Comment by 941477276** [comment]
`const app = createApp();` 调用createApp函数时要传参的

**Comment by zwsn** [comment]
createApp(App).component(Vue3CountryIntl.name, Vue3CountryIntl);

**Comment by 941477276** [comment]
你试试这样
```
/*****main.js****/
import Vue3CountryIntl from 'vue3-country-intl';
// 引入css
import 'vue3-country-intl/lib/vue3-country-intl.css'
import App from './App.vue';

const app = createApp(App);

// 全局注册组件
app.component(Vue3CountryIntl.name, Vue3CountryIntl);

app.mount('#app')
```

**Comment by zwsn** [comment]
🙏 可以了
