### ISSUE TITLE
选择🇺🇸的时候总是一次显示成🇨🇦，第二次才会正常

### ISSUE THREAD

**Issue by backApril** [941477276/vue-country-intl#33]
选择🇺🇸的时候总是一次显示成🇨🇦，第二次才会正常

**Comment by 941477276** [comment]
`United States`这个国家吗？

**Comment by 941477276** [comment]
麻烦描述的具体一点，最好带图片

**Comment by backApril** [comment]
是的United States这个国家，在你演示的页面里，input模式4号和一号选择表现不一致，4号选择United States会编程canada，1不会

**Comment by 941477276** [comment]
没发现呀，你录个gif图来看下

**Comment by 941477276** [comment]
`1.0.31`版本已修复
