### ISSUE TITLE
选择country模式返回的值问题

### ISSUE THREAD

**Issue by azhu949** [941477276/vue-country-intl#35]
目前使用country模式后选择中国 返回的值为cn，期望能返回中国并且存放在数据库后页面能正常回显，请问有相关的配置吗？

**Comment by 941477276** [comment]
`onChange`事件可以获取的到完整的国籍信息，你可以通过`onChange`事件取得国籍名称。回显效果必须通过国籍编码或区号，数据库中存储国籍名称和国籍编码你的问题就解决了

**Comment by azhu949** [comment]
请问在标签上定义了onChange事件在方法里面如何获取到值呢？
<vue-country-intl v-model="form.country" type="country" placeholder="请选择或搜索国籍" onchange="countryChange()"></vue-country-intl>
countryChange(){
      // console.log("获取到数据")
    }

**Comment by 941477276** [comment]
```
countryChange(countryInfo){
  console.log("获取到数据", countryInfo);
}
```

**Comment by azhu949** [comment]
![image](https://user-images.githubusercontent.com/51523658/174703134-f4b081bb-7e66-4f73-802e-abd96d07fa58.png)
![image](https://user-images.githubusercontent.com/51523658/174703185-21cfe071-96a5-4c74-821c-647504107609.png)
![image](https://user-images.githubusercontent.com/51523658/174703209-2c9c0f7c-ab87-4fde-88b2-3e6f2c15c9eb.png)
控制台并没有打印相关信息，是不是我方法定义有问题？

**Comment by 941477276** [comment]
`<vue-country-intl v-model="form.country" type="country" placeholder="请选择或搜索国籍" @onChange="countryChange"></vue-country-intl>`

**Comment by azhu949** [comment]
非常感谢您的解答，前端这一块不是很懂，也感谢您提供这么优秀的组件！
