### ISSUE TITLE
nuxt 中为啥引入不行哎？求大佬解答，谢谢，对vue 不是很熟悉

### ISSUE THREAD

**Issue by 424363283** [941477276/vue-country-intl#36]
vue-country-intl
![image](https://user-images.githubusercontent.com/26781516/217268057-937627eb-9d43-442d-ad6f-37607e2e76b4.png)
![image](https://user-images.githubusercontent.com/26781516/217268111-120c7c03-4333-4a9d-b6aa-5b8ca25173c0.png)

**Comment by 424363283** [comment]
用了之后是这样
![image](https://user-images.githubusercontent.com/26781516/217268310-3d3b0086-a96c-4518-84a0-73f9259bf489.png)

**Comment by 941477276** [comment]
图标不显示出来是吗？你检查下元素并截图，然后再截张浏览器控制台的截图

**Comment by 941477276** [comment]
或者你给个简单的demo给我
