### ISSUE TITLE
后续会支持 useChinese 以中文显示国籍名称 时 兼容 所搜值 nameCN 对应的数据么 

### ISSUE THREAD

**Issue by IoTCard** [941477276/vue-country-intl#38]
![image](https://github.com/941477276/vue-country-intl/assets/128167683/1b7823b8-82f9-419b-b791-032c559dcecc)

**Comment by 941477276** [comment]
`1.1.4`版本已解决该问题

**Comment by IoTCard** [comment]
感谢回复！

**Comment by IoTCard** [comment]
大牛真心不错，昨天提的issues 今天就 更新版本了！
![image](https://github.com/941477276/vue-country-intl/assets/128167683/27fc70d3-58f2-4ca3-b652-501cf75e32c2)
