### ISSUE TITLE
Vuejs v3 version

### ISSUE THREAD

**Issue by taozuhong** [941477276/vue-country-intl#45]
这个组件很赞，唯一遗憾的就是没有支持 Vuejs 3.x。

可否升级支持 Vuejs 3.x 版本系列呢？

**Comment by 941477276** [comment]
有`Vue3.x`版本的，链接：https://github.com/941477276/vue3-country-intl

**Comment by taozuhong** [comment]
嗯，用上了，谢谢您的慷慨分享。
