### ISSUE TITLE
不支持TS\

### ISSUE THREAD

**Issue by ahmiao666** [941477276/vue-country-intl#51]
无法找到模块“vue-country-intl”的声明文件。“d:/tahi-ex_app4-vue3/node_modules/vue-country-intl/lib/vue-country-intl.min.js”隐式拥有 "any" 类型。

**Comment by iLalGold** [comment]
![Snipaste_2024-08-27_17-27-01](https://github.com/user-attachments/assets/c5976ab8-eec4-4b71-b73a-dcbaac0c62de)

**Comment by iLalGold** [comment]
> ![Snipaste_2024-08-27_17-27-01](https://private-user-images.githubusercontent.com/84552314/361763250-c5976ab8-eec4-4b71-b73a-dcbaac0c62de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NTQ3MzcsIm5iZiI6MTcyNDc1NDQzNywicGF0aCI6Ii84NDU1MjMxNC8zNjE3NjMyNTAtYzU5NzZhYjgtZWVjNC00YjcxLWI3M2EtZGNiYWFjMGM2MmRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDEwMjcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkZTE0OGZhNTczMDQ0OTU4YTBjMTdmOTgzOTkxOTE1NjQyNTA2MzhkZjgwOWEyOTE2YmMyMjlmNzFmZmQzYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z4kD3ckdiHWZOrNW4iDgxBWI4vXtGn4LwmPzNLNz9UI)

只能通过这样的方式强制让他不报错

**Comment by 941477276** [comment]
先在导入组件的地方加上`// @ts-ignore`忽略TS报错吧，一开始没用TS开发
