### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by ping-an-na** [941477276/vue-country-intl#53]
最新更新的 ”1.1.7“ 版本中 出现报错。Error undefined:1:2203:missing ”}“ 。

**Comment by 941477276** [comment]
我刚试了下没有发现报错，你使用的是vue2还是vue3？如果是vue3，请使用`vue3-country-intl`。如果是vue2报错，请贴下复现代码

**Comment by ping-an-na** [comment]
这是使用docker 部署的时候 cnpm打包时报错，因为cnpm有诡异bug，我不确定错误原因，我复述一下过程。
 
之前写的是 package.json 里写的是 "vue-country-intl": "^1.1.4", 因为^ 原因，总是打包最新版 所以 我尝试了两种原因方法 一个是用的npm（我看了源码里面也是只到 1.1.6 不知道为什么不是1.1.7），第二种就是去掉角标 写死的 1.1.6 然后尝试打包，同样可以解决问题。如果是用1.1.7 打包就会出现上述的报错。
| |
张风辉
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 9/23/2024 15:23 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [941477276/vue-country-intl] BUG (Issue #53) |

我刚试了下没有发现报错，你使用的是vue2还是vue3？如果是vue3，请使用vue3-country-intl。如果是vue2报错，请贴下复现代码

**Comment by ping-an-na** [comment]
额，因为收到了邮件，我用邮箱回复的，邮箱有发图片，在这里看起来可能有点乱...

**Comment by 941477276** [comment]
估计是cnpm缓存原因，获取`package-lock.json`的原因，你清理下cnpm缓存或把`package-lock.json`删掉试试。我本地安装的包里的版本号是`1.1.7`
![image](https://github.com/user-attachments/assets/68767eb1-a6d4-45d6-8d53-9a8f1b9987aa)

**Comment by ping-an-na** [comment]
我想做一个简易的demo复现一下，遗憾我没能复现出来，暂时我认为可能是组件冲突，（因为项目较大各种各样的不认识的组件），所以看了下源码对照报错的地方，有个地方想请教下，这个地方是css文件 怎么使用的Sass语法。
![1727083132094](https://github.com/user-attachments/assets/a8e7f147-173a-4dfd-a473-6ef7432badfa)

**Comment by 941477276** [comment]
习惯了使用scss，写的时候没注意。一些较新的浏览器已经支持这种写法了，旧版浏览器不会报错但没效果

**Comment by ping-an-na** [comment]
![1727084474291](https://github.com/user-attachments/assets/46fe145b-0e06-4964-9110-4bb16023c74d)
大佬这里可以规范一下，测试了几次是 postcss-px2rem 组件导致的（px 转 rem 一种屏幕自适应的解决方案）（可难用了）应该是强校验了css文件因为不规范报错了。

**Comment by 941477276** [comment]
嗯，晚点我更新个版本

**Comment by 941477276** [comment]
刚更新了版本，升级到`1.1.8`版本即可解决
